substitutions:
  _TEST0_ID: "5318999b-4210-42b5-97ce-88fcd687cb63"
  _TEST0_STATS: '{"difficulty":{"max":51054419,"standardDeviation":296856.2473503099,"mean":50341256.42326733},"totalDifficulty":{"max":20944504816,"standardDeviation":5867274706.832206,"mean":10771093839.502472},"gasLimit":{"max":11850000,"standardDeviation":0,"mean":11850000},"gasUsed":{"max":11368968,"standardDeviation":1621.888402328743,"mean":11365087.445544545},"blockTime":{"max":81,"standardDeviation":12.98366888644951,"mean":12.004962779156328},"blockSize":{"max":163731,"standardDeviation":38.57765819985944,"mean":163202.25742574254},"transactionPerBlock":{"max":25,"standardDeviation":0,"mean":25},"uncleCount":{"max":1,"standardDeviation":0.07018538058791002,"mean":0.0049504950495049445},"tps":{"max":25,"standardDeviation":7.560987577479733,"mean":6.578585527039876},"blocks":404}'
  _TEST0_DATE: "2020-08-29"
  _TEST1_ID: "8828a1b2-48d2-49bb-a92f-0d7b799ec346"
  _TEST1_STATS: '{"difficulty":{"max":51904332,"standardDeviation":289151.6013979661,"mean":51423420.227817744},"totalDifficulty":{"max":21956497003,"standardDeviation":6198112290.060109,"mean":11233770472.004791},"gasLimit":{"max":45450000,"standardDeviation":0,"mean":45450000},"gasUsed":{"max":45015384,"standardDeviation":3112.7582499181467,"mean":45005516.02877694},"blockTime":{"max":77,"standardDeviation":12.045785089588646,"mean":12.120192307692305},"blockSize":{"max":645379,"standardDeviation":89.68453383621384,"mean":644767.3836930451},"transactionPerBlock":{"max":99,"standardDeviation":0,"mean":99},"uncleCount":{"max":1,"standardDeviation":0.097469551236938,"mean":0.00959232613908872},"tps":{"max":99,"standardDeviation":27.143834028919425,"mean":22.70960060741762},"blocks":417}'
  _TEST1_DATE: "2020-08-30"
  _ACCOUNT_PASSWORD: "password"
  _ETH_NETWORK_ID: "7777"
  _ACCOUNTS_TO_CREATE: "90"  # should be same as num. nodes
  _BA_PARAMETER: "10"
  _GAS_LIMIT:  45450000
  _GAS_TARGET: 45000000
  _TPS: 4  # per node, pick sufficiently high rate for saturation 
  _TX_SIZE: 6400
  _CONCURRENT_NONCES: 75    # don't set too high to ensure steady tx saturation (must be less than Geth's `--txpool.accountslots`).
services:
  - name: geth
    image: "ethereum/client-go:alltools-v1.9.18"
#    image: "gcr.io/whiteblock/geth-wb/geth:v1.9.18"
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: >
        mkdir -p /geth/keystore;
        cp /accounts/keystore/* /geth/keystore;
        cp /accounts/static-nodes${INDEX}.json /geth/static-nodes.json;
        echo $_ACCOUNT_PASSWORD > /geth/pw.txt;
        geth --nousb --datadir /geth/ init /accounts/genesis.json;
        geth --networkid $_ETH_NETWORK_ID
        --datadir /geth/
        --http
        --http.addr 0.0.0.0
        --miner.gasprice=${MINER_GASPRICE}
        --miner.gaslimit=$_GAS_LIMIT
        --miner.gastarget=$_GAS_TARGET
        --http.api "admin,web3,eth,net,personal,miner,txpool"
        --http.corsdomain "0.0.0.0"
        --txpool.nolocals
        --http.vhosts=*
        --verbosity=3
        --port 30303
        --nousb
        --miner.etherbase $(cat /accounts/address${INDEX})
        --unlock $(cat /accounts/address${INDEX})
        --allow-insecure-unlock
        --password /geth/pw.txt
        --mine
        --miner.threads=${MINER_THREADS}
        --nodekeyhex $(cat /accounts/priv$INDEX)
        --nodiscover
        --txpool.accountslots 5000
    environment:
      MINER_GASPRICE: "1"
      MINER_THREADS: "1"
    resources:
      cpus: 2
      memory: 6 GB
      storage: 40 GiB
  
  - name: record
    image: gcr.io/whiteblock/helpers/ethereum/record:master
    script:
      inline: 
        app --target http://$GETH_SERVICE0_COMMON_NETWORK:8545 --start-block 10
    resources:
      memory: 1 GiB

  - name: block-logger
    image: gcr.io/whiteblock/helpers/ethereum/block-logger:master
    script:
      inline: 
        app --target http://$GETH_SERVICE0_COMMON_NETWORK:8545 --delay 10
    resources:
      memory: 1 GiB

  - name: tps-logger
    image: gcr.io/whiteblock/helpers/ethereum/tps-logger:master
    script:
      inline: tps-logger --node $GETH_SERVICE0_COMMON_NETWORK:8545 --record $RECORD_SERVICE0_COMMON_NETWORK:8080 --listen 0.0.0.0:17777
    resources:
      memory: 1 GiB

  - name: eth-viewer
    image: gcr.io/whiteblock/helpers/ethereum/viewer:latest
    script:
      inline: viewer --node $GETH_SERVICE0_COMMON_NETWORK:8545 --listen 0.0.0.0:16555
    resources:
      memory: 1 GiB

sidecars:
  - name: tx-generator
    sidecar-to:
      - geth
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    image: gcr.io/whiteblock/helpers/ethereum/tx:ef
    script:
      # recvAddrs${INDEX}.json will be comma separated addresses with 0x prefix
      inline: >
        cat /accounts/accounts.json 
        | jq --arg i "${INDEX}" 'del(.[$i | tonumber]) | map(.address) | join(",")' 
        > /accounts/recvAddrs${INDEX}.json;
        privkey=$(cat /accounts/accounts.json | jq --arg i "${INDEX}" '.[$i | tonumber].privateKey');
        tx --chain-id $_ETH_NETWORK_ID 
        --tps $_TPS
        --target $SERVICE:8545 
        --private-key ${privkey} 
        --gas-limit ${TX_GAS_LIMIT} 
        --tx-size $_TX_SIZE
        --gas-price ${TX_GAS_PRICE}
        --destination $(cat /accounts/recvAddrs${INDEX}.json)
        --concurrent-nonces $_CONCURRENT_NONCES
    environment:
      TX_GAS_PRICE: "500000"
      TX_GAS_LIMIT: "550000"
    resources:
      cpus: 2
      memory: 3 GB

task-runners:
  - name: generate-accounts
    image: "gcr.io/whiteblock/helpers/ethereum/accounts:master"
    script:
      inline: accounts generate -c $_ACCOUNTS_TO_CREATE -e -d /accounts
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    resources:
      memory: 2 GB

  - name: generate-genesis
    image: gcr.io/whiteblock/helpers/ethereum/genesis:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
#    environment:
    script:
      inline: genesis generate -a /accounts/accounts.json -o consensus=ethash -o gasLimit=$_GAS_LIMIT -o difficulty=55000000 | tee /accounts/genesis.json
    resources:
      memory: 2 GB
  - name: generate-static-peers
    image: gcr.io/whiteblock/helpers/ethereum/static-peers:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script: 
      inline: generate --accounts-file /accounts/accounts.json --network common-network --service geth | tee /accounts/static-nodes.json
 
  - name: generate-topology
    image: gcr.io/whiteblock/helpers/ethereum/topology:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: python generate.py /accounts/static-nodes.json /accounts/ $_ACCOUNTS_TO_CREATE $_BA_PARAMETER 54321 50

  - name: generate-keystore
    image: gcr.io/whiteblock/helpers/geth/keystore:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: >
        echo $_ACCOUNT_PASSWORD > /tmp/pw.txt;
        keystore -p /tmp/pw.txt -f /accounts/accounts.json -o /accounts/keystore/
    resources:
      cpus: 2
      memory: 2 GB

  - name: await-block-production
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545
    resources:
      memory: 1 GB

  - name: await-blocks-$_PHASE_ONE_BLOCKS
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545 --block $_PHASE_ONE_BLOCKS
    resources:
      memory: 1 GB

tests: 
  - name: geth_demo
    phases:
      - name: generating-accounts
        tasks: 
        - type: generate-accounts
      
      - name: creating-keystore-genesis-static-peers
        tasks:
          - type: generate-genesis
          - type: generate-keystore
          - type: generate-static-peers

      - name: setup-topology
        tasks:
          - type: generate-topology
      
      - name: starting-geth-nodes
        system:
          - type: geth
            count: 90 # <---------------------------------------------
            resources:
              networks:
                - name: common-network
                  bandwidth: 100 Mbit
#                  latency: 50 ms
      
      - name: awaiting-block-production
        tasks:
          - type: await-block-production
            timeout: 30m
            networks:
              - name: common-network

      - name: starting-stats-tools
        system:
        - type: record
          port-mappings:
            - "8080:8080"
          resources:
            networks:
              - name: common-network

      - name: start-custom-viewers
        duration: 120m #wait 120 minutes before checking for tx completion
        system:
        - type: tps-logger 
          port-mappings:
            - "17777:17777"
          resources:
            networks:
              - name: common-network
        - type: block-logger
          resources:
            networks:
              - name: common-network
        - type: eth-viewer
          port-mappings:
            - "16555:16555"
          resources:
            networks:
              - name: common-network
