substitutions:
  _TEST0_ID: "a9530a40-c63c-4015-954c-a0ea87ed065a"
  _TEST0_STATS: '{"difficulty":{"max":51541451,"standardDeviation":496313.73504470097,"mean":50617553.58612438},"totalDifficulty":{"max":21665844286,"standardDeviation":6102214087.174406,"mean":11056053820.468904},"gasLimit":{"max":3300000,"standardDeviation":0,"mean":3300000},"gasUsed":{"max":3184888,"standardDeviation":838.7156138188288,"mean":3182135.8468899517},"blockTime":{"max":64,"standardDeviation":11.516091905092413,"mean":11.40767386091127},"blockSize":{"max":46625,"standardDeviation":26.392136749684344,"mean":46086.33971291864},"transactionPerBlock":{"max":7,"standardDeviation":0,"mean":7},"uncleCount":{"max":1,"standardDeviation":0.0488530570733544,"mean":0.0023923444976076554},"tps":{"max":7,"standardDeviation":2.1611337092651013,"mean":1.8788276328903841},"blocks":418}'
  _TEST0_DATE: "2020-09-04"
  _TEST1_ID: "1ab5099d-b3aa-45f1-9061-b559231c13d5"
  _TEST1_STATS: '{"difficulty":{"max":50429684,"standardDeviation":120954.40961213004,"mean":50110437.06971156},"totalDifficulty":{"max":21351646659,"standardDeviation":6019003743.941931,"mean":10947101214.41827},"gasLimit":{"max":3300000,"standardDeviation":0,"mean":3300000},"gasUsed":{"max":3184376,"standardDeviation":790.5972875022516,"mean":3182212.923076923},"blockTime":{"max":85,"standardDeviation":12.327148926971363,"mean":12.156626506024091},"blockSize":{"max":46625,"standardDeviation":78.27098634719592,"mean":46096.68028846155},"transactionPerBlock":{"max":7,"standardDeviation":0,"mean":7},"uncleCount":{"max":1,"standardDeviation":0.14548731491705785,"mean":0.021634615384615384},"tps":{"max":7,"standardDeviation":2.0805726381433374,"mean":1.764705929131351},"blocks":416}'
  _TEST1_DATE: "2020-09-04"
  _ACCOUNT_PASSWORD: "password"
  _ETH_NETWORK_ID: "7777"
  _ACCOUNTS_TO_CREATE: "90"  # should be same as num. nodes
  _BA_PARAMETER: "4"
  _GAS_LIMIT:  3300000
  _GAS_TARGET: 2950000
  _TPS: 4  # per node, pick sufficiently high rate for saturation 
  _TX_SIZE: 6400
  _CONCURRENT_NONCES: 75    # don't set too high to ensure steady tx saturation (must be less than Geth's `--txpool.accountslots`).
services:
  - name: geth
    image: "ethereum/client-go:alltools-v1.9.18"
#    image: "gcr.io/whiteblock/geth-wb/geth:v1.9.18"
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: >
        mkdir -p /geth/keystore;
        cp /accounts/keystore/* /geth/keystore;
        cp /accounts/static-nodes${INDEX}.json /geth/static-nodes.json;
        echo $_ACCOUNT_PASSWORD > /geth/pw.txt;
        geth --nousb --datadir /geth/ init /accounts/genesis.json;
        geth --networkid $_ETH_NETWORK_ID
        --datadir /geth/
        --http
        --http.addr 0.0.0.0
        --miner.gasprice=${MINER_GASPRICE}
        --miner.gaslimit=$_GAS_LIMIT
        --miner.gastarget=$_GAS_TARGET
        --http.api "admin,web3,eth,net,personal,miner,txpool"
        --http.corsdomain "0.0.0.0"
        --txpool.nolocals
        --http.vhosts=*
        --verbosity=3
        --port 30303
        --nousb
        --miner.etherbase $(cat /accounts/address${INDEX})
        --unlock $(cat /accounts/address${INDEX})
        --allow-insecure-unlock
        --password /geth/pw.txt
        --mine
        --miner.threads=${MINER_THREADS}
        --nodekeyhex $(cat /accounts/priv$INDEX)
        --nodiscover
        --txpool.accountslots 5000
    environment:
      MINER_GASPRICE: "1"
      MINER_THREADS: "1"
    resources:
      cpus: 2
      memory: 6 GB
      storage: 40 GiB
  
  - name: record
    image: gcr.io/whiteblock/helpers/ethereum/record:master
    script:
      inline: 
        app --target http://$GETH_SERVICE0_COMMON_NETWORK:8545 --start-block 10
    resources:
      memory: 1 GiB

  - name: block-logger
    image: gcr.io/whiteblock/helpers/ethereum/block-logger:master
    script:
      inline: 
        app --target http://$GETH_SERVICE0_COMMON_NETWORK:8545 --delay 10
    resources:
      memory: 1 GiB

  - name: tps-logger
    image: gcr.io/whiteblock/helpers/ethereum/tps-logger:master
    script:
      inline: tps-logger --node $GETH_SERVICE0_COMMON_NETWORK:8545 --record $RECORD_SERVICE0_COMMON_NETWORK:8080 --listen 0.0.0.0:17777
    resources:
      memory: 1 GiB

  - name: eth-viewer
    image: gcr.io/whiteblock/helpers/ethereum/viewer:latest
    script:
      inline: viewer --node $GETH_SERVICE0_COMMON_NETWORK:8545 --listen 0.0.0.0:16555
    resources:
      memory: 1 GiB

sidecars:
  - name: tx-generator
    sidecar-to:
      - geth
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    image: gcr.io/whiteblock/helpers/ethereum/tx:ef
    script:
      # recvAddrs${INDEX}.json will be comma separated addresses with 0x prefix
      inline: >
        cat /accounts/accounts.json 
        | jq --arg i "${INDEX}" 'del(.[$i | tonumber]) | map(.address) | join(",")' 
        > /accounts/recvAddrs${INDEX}.json;
        privkey=$(cat /accounts/accounts.json | jq --arg i "${INDEX}" '.[$i | tonumber].privateKey');
        tx --chain-id $_ETH_NETWORK_ID 
        --tps $_TPS
        --target $SERVICE:8545 
        --private-key ${privkey} 
        --gas-limit ${TX_GAS_LIMIT} 
        --tx-size $_TX_SIZE
        --gas-price ${TX_GAS_PRICE}
        --destination $(cat /accounts/recvAddrs${INDEX}.json)
        --concurrent-nonces $_CONCURRENT_NONCES
    environment:
      TX_GAS_PRICE: "500000"
      TX_GAS_LIMIT: "550000"
    resources:
      cpus: 2
      memory: 3 GB

task-runners:
  - name: generate-accounts
    image: "gcr.io/whiteblock/helpers/ethereum/accounts:master"
    script:
      inline: accounts generate -c $_ACCOUNTS_TO_CREATE -e -d /accounts
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    resources:
      memory: 2 GB

  - name: generate-genesis
    image: gcr.io/whiteblock/helpers/ethereum/genesis:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
#    environment:
    script:
      inline: genesis generate -a /accounts/accounts.json -o consensus=ethash -o gasLimit=$_GAS_LIMIT -o difficulty=55000000 | tee /accounts/genesis.json
    resources:
      memory: 2 GB
  - name: generate-static-peers
    image: gcr.io/whiteblock/helpers/ethereum/static-peers:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script: 
      inline: generate --accounts-file /accounts/accounts.json --network common-network --service geth | tee /accounts/static-nodes.json
 
  - name: generate-topology
    image: gcr.io/whiteblock/helpers/ethereum/topology:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: python generate.py /accounts/static-nodes.json /accounts/ $_ACCOUNTS_TO_CREATE $_BA_PARAMETER 54321 50

  - name: generate-keystore
    image: gcr.io/whiteblock/helpers/geth/keystore:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: >
        echo $_ACCOUNT_PASSWORD > /tmp/pw.txt;
        keystore -p /tmp/pw.txt -f /accounts/accounts.json -o /accounts/keystore/
    resources:
      cpus: 2
      memory: 2 GB

  - name: await-block-production
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545
    resources:
      memory: 1 GB

  - name: await-blocks-$_PHASE_ONE_BLOCKS
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545 --block $_PHASE_ONE_BLOCKS
    resources:
      memory: 1 GB

tests: 
  - name: geth_demo
    phases:
      - name: generating-accounts
        tasks: 
        - type: generate-accounts
      
      - name: creating-keystore-genesis-static-peers
        tasks:
          - type: generate-genesis
          - type: generate-keystore
          - type: generate-static-peers

      - name: setup-topology
        tasks:
          - type: generate-topology
      
      - name: starting-geth-nodes
        system:
          - type: geth
            count: 90 # <---------------------------------------------
            resources:
              networks:
                - name: common-network
                  bandwidth: 25 Mbit
                  latency: 150 ms
                  packet-loss: .01
      - name: awaiting-block-production
        tasks:
          - type: await-block-production
            timeout: 30m
            networks:
              - name: common-network

      - name: starting-stats-tools
        system:
        - type: record
          port-mappings:
            - "8080:8080"
          resources:
            networks:
              - name: common-network

      - name: start-custom-viewers
        duration: 120m #wait 120 minutes before checking for tx completion
        system:
        - type: tps-logger 
          port-mappings:
            - "17777:17777"
          resources:
            networks:
              - name: common-network
        - type: block-logger
          resources:
            networks:
              - name: common-network
        - type: eth-viewer
          port-mappings:
            - "16555:16555"
          resources:
            networks:
              - name: common-network
